import os

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from src.inference import predict_customer


# ----------------------------------------------------------
# Application
# ----------------------------------------------------------

app = FastAPI(
    title="KINETICS API",
    description=(
        "Customer Behavior & Churn Intelligence API. "
        "Provides churn prediction and explainable ML insights."
    ),
    version="1.0.0",
)


# ----------------------------------------------------------
# CORS
# ----------------------------------------------------------

frontend_url = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173",
)

allowed_origins = [
    frontend_url,
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Remove duplicates while preserving order.
allowed_origins = list(dict.fromkeys(allowed_origins))

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----------------------------------------------------------
# Request Schema
# ----------------------------------------------------------

class CustomerInput(BaseModel):
    """
    Customer attributes expected by the trained KINETICS
    inference pipeline.

    ServiceCount and AverageMonthlySpend are engineered
    features generated by the KINETICS feature-engineering
    pipeline.
    """

    gender: str = Field(..., min_length=1)
    SeniorCitizen: int = Field(..., ge=0, le=1)

    Partner: str = Field(..., min_length=1)
    Dependents: str = Field(..., min_length=1)

    tenure: float = Field(..., ge=0)

    PhoneService: str = Field(..., min_length=1)
    MultipleLines: str = Field(..., min_length=1)

    InternetService: str = Field(..., min_length=1)

    OnlineSecurity: str = Field(..., min_length=1)
    OnlineBackup: str = Field(..., min_length=1)
    DeviceProtection: str = Field(..., min_length=1)
    TechSupport: str = Field(..., min_length=1)

    StreamingTV: str = Field(..., min_length=1)
    StreamingMovies: str = Field(..., min_length=1)

    Contract: str = Field(..., min_length=1)
    PaperlessBilling: str = Field(..., min_length=1)

    PaymentMethod: str = Field(..., min_length=1)

    MonthlyCharges: float = Field(..., ge=0)
    TotalCharges: float = Field(..., ge=0)

    ServiceCount: float = Field(..., ge=0)
    AverageMonthlySpend: float = Field(..., ge=0)


# ----------------------------------------------------------
# Root
# ----------------------------------------------------------

@app.get("/")
def root():
    return {
        "name": "KINETICS API",
        "description": (
            "Customer Behavior & Churn "
            "Intelligence Platform"
        ),
        "version": "1.0.0",
        "status": "running",
    }


# ----------------------------------------------------------
# Health Check
# ----------------------------------------------------------

@app.get("/health")
def health():
    return {
        "status": "healthy",
        "model": "gradient_boosting_tuned",
        "inference": "ready",
    }


# ----------------------------------------------------------
# Prediction
# ----------------------------------------------------------

@app.post("/predict")
def predict(customer: CustomerInput):
    """
    Run the trained KINETICS churn model.

    Returns:
    - churn probability
    - prediction
    - risk level
    - local SHAP explanation
    - global feature drivers
    """

    try:
        customer_data = customer.model_dump()

        result = predict_customer(
            customer_data
        )

        return {
            "success": True,
            "result": result,
        }

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=500,
            detail=(
                "Required model or inference artifact "
                f"was not found: {exc}"
            ),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=(
                "Prediction failed. "
                f"{type(exc).__name__}: {exc}"
            ),
        ) from exc